#
###################################
# Site wide configuration
####################################
#
title: Ruby para todos
email: brunopereiras@icloud.com
description: Aprenda lógica de programação e orientacão a objetos usando Ruby on Rails
url: https://rubyparatodos.netlify.com/ # the base hostname & protocol for your site
keywords: ["Lógica de programação", "Ruby on Rails", "Ruby", "ROR", "Orientação a objetos", "Algoritmos"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Sao_Paulo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ruby para todos
  avatar:
  job: "Algoritmos com ruby on rails"
  bio: "Aprenda lógica de programação e orientacão a objetos usando Ruby on Rails."
  email: brunopereiras@icloud.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: brunopereiras #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: brunopereiras #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
